services:
  # 1. Your Flask Backend Server
  - type: web
    name: ssuet-survey-backend
    env: python
    buildCommand: ./render-build.sh
    startCommand: export PATH="${PATH}:/opt/render/project/.render/chrome/opt/google/chrome" && python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  # 2. Your HTML Frontend Web Page
  - type: static
    name: ssuet-survey-frontend
    env: static
    buildCommand: "" 
    publishDir: "."  
    routes:
      - type: rewrite
        src: /api/*
        dest: https://ssuet-survey-backend.onrender.com/api/*